export const gamesData = [
  {
    id: 'gta-sa',
    name: 'GTA San Andreas',
    image: 'https://cdn.poehali.dev/projects/a5a6bbac-c8c2-43be-b5cd-e4454e318ae4/files/e6fda6ad-4058-4ba7-93e8-49b38123d116.jpg',
    description: 'Легендарная игра с открытым миром'
  },
  {
    id: 'sims4',
    name: 'The Sims 4',
    image: 'https://cdn.poehali.dev/projects/a5a6bbac-c8c2-43be-b5cd-e4454e318ae4/files/2f914ff7-3f32-4bf5-8d89-b19c7383b0c9.jpg',
    description: 'Симулятор жизни от EA Games'
  },
  {
    id: 'gmod',
    name: "Garry's Mod",
    image: 'https://cdn.poehali.dev/projects/a5a6bbac-c8c2-43be-b5cd-e4454e318ae4/files/5896de38-8a52-4650-9734-4fe6446ad7fe.jpg',
    description: 'Песочница с безграничными возможностями'
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    image: 'https://cdn.poehali.dev/projects/a5a6bbac-c8c2-43be-b5cd-e4454e318ae4/files/cb54d5cf-189d-4aae-8e08-90484e164809.jpg',
    description: 'Создавай и исследуй кубический мир'
  },
  {
    id: 'terraria',
    name: 'Terraria',
    image: 'https://cdn.poehali.dev/projects/a5a6bbac-c8c2-43be-b5cd-e4454e318ae4/files/ef2da7e4-c45a-4dcc-a2be-511572b4c911.jpg',
    description: '2D приключения и выживание'
  }
];

export const gamesList = gamesData.map(g => g.name);

export const contentTypes = [
  { id: 'download', name: 'Скачать', icon: 'Download', subcategories: ['Оригинал', 'Сборка'] },
  { id: 'mods', name: 'Моды', icon: 'Package', subcategories: ['Оружие', 'Транспорт', 'Карты', 'Скины', 'Персонажи'] },
  { id: 'scripts', name: 'Скрипты', icon: 'Code' },
  { id: 'cheats', name: 'Читы', icon: 'Shield' },
  { id: 'info', name: 'Информация', icon: 'Info' },
];

export const categories = [
  { id: 'games', name: 'Игры', icon: 'Gamepad2', color: 'text-[hsl(var(--primary))]' },
];

export const mockFiles = [
  {
    id: 1,
    name: 'GTA San Andreas - Оригинал',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '4.7 GB',
    downloads: 125420,
    rating: 4.9,
    version: '1.0',
    fileUrl: 'https://drive.google.com/drive/folders/1E-XC8YotGM2ehlbZPN8Qmi_rtxg4NerB?usp=drive_link',
    fileType: 'direct',
  },
  {
    id: 2,
    name: 'GTA San Andreas - Сборка',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '8.2 GB',
    downloads: 98340,
    rating: 4.8,
    version: '2.0',
    fileUrl: 'https://drive.google.com/file/d/1K39kTz6Eoof3wD24SnBQKGkbAKIajyQd/view?usp=drive_link',
    fileType: 'direct',
  },
  {
    id: 3,
    name: 'GTA San Andreas - Аддоны',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'mods',
    downloadType: null,
    modType: 'Карты',
    size: '1.5 GB',
    downloads: 45230,
    rating: 4.7,
    version: '1.0',
    fileUrl: 'https://drive.google.com/drive/folders/1BJHA14OsTQydJnSpD3VzsAqsekf7Qsvd?usp=drive_link',
    fileType: 'direct',
  },
  {
    id: 4,
    name: 'The Sims 4 - Оригинал',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '18 GB',
    downloads: 98340,
    rating: 4.7,
    version: '1.98',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 5,
    name: 'The Sims 4 - Сборка со всеми DLC',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '45 GB',
    downloads: 156780,
    rating: 4.9,
    version: '1.98',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 6,
    name: 'The Sims 4 - Аддоны',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'mods',
    downloadType: null,
    modType: 'Карты',
    size: '2.3 GB',
    downloads: 34120,
    rating: 4.6,
    version: '1.0',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 7,
    name: 'Minecraft - TLauncher',
    category: 'games',
    game: 'Minecraft',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '250 MB',
    downloads: 234560,
    rating: 4.8,
    version: '1.20.4',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 8,
    name: 'Minecraft - KLauncher',
    category: 'games',
    game: 'Minecraft',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '180 MB',
    downloads: 87340,
    rating: 4.6,
    version: '1.20.4',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 9,
    name: 'Minecraft - Mister Launcher',
    category: 'games',
    game: 'Minecraft',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '220 MB',
    downloads: 45120,
    rating: 4.5,
    version: '1.20.4',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 10,
    name: 'Minecraft - Сборка',
    category: 'games',
    game: 'Minecraft',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '3.2 GB',
    downloads: 156890,
    rating: 4.9,
    version: '1.20.4',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 11,
    name: 'Minecraft - Аддоны',
    category: 'games',
    game: 'Minecraft',
    contentType: 'mods',
    downloadType: null,
    modType: 'Карты',
    size: '890 MB',
    downloads: 78450,
    rating: 4.7,
    version: '1.0',
    fileUrl: '',
    fileType: 'direct',
  },
];