export const gamesList = ['GTA San Andreas', 'The Sims 4', "Garry's Mod", 'Minecraft', 'Terraria'];

export const contentTypes = [
  { id: 'download', name: 'Скачать', icon: 'Download', subcategories: ['Оригинал', 'Сборка'] },
  { id: 'mods', name: 'Моды', icon: 'Package', subcategories: ['Оружие', 'Транспорт', 'Карты', 'Скины', 'Персонажи'] },
  { id: 'scripts', name: 'Скрипты', icon: 'Code' },
  { id: 'cheats', name: 'Читы', icon: 'Shield' },
  { id: 'info', name: 'Информация', icon: 'Info' },
];

export const categories = [
  { id: 'games', name: 'Игры', icon: 'Gamepad2', color: 'text-[hsl(var(--primary))]' },
];

export const mockFiles = [
  {
    id: 1,
    name: 'GTA San Andreas - Оригинал',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '4.7 GB',
    downloads: 125420,
    rating: 4.9,
    version: '1.0',
    fileUrl: 'https://drive.google.com/uc?export=download&id=1K39kTz6Eoof3wD24SnBQKGkbAKIajyQd',
    fileType: 'direct',
  },
  {
    id: 14,
    name: 'GTA San Andreas - Сборка с модами',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '8.2 GB',
    downloads: 98340,
    rating: 4.8,
    version: '2.0',
  },
  {
    id: 2,
    name: 'GTA San Andreas - Сохранения 100%',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'info',
    downloadType: null,
    modType: null,
    size: '12 MB',
    downloads: 45230,
    rating: 4.6,
    version: '1.0',
  },
  {
    id: 3,
    name: 'The Sims 4 - Оригинал',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '18 GB',
    downloads: 98340,
    rating: 4.7,
    version: '1.98',
  },
  {
    id: 15,
    name: 'The Sims 4 - Сборка со всеми DLC',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '45 GB',
    downloads: 156780,
    rating: 4.9,
    version: '1.98',
  },
  {
    id: 4,
    name: 'The Sims 4 - Мебель и декор',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'mods',
    downloadType: null,
    modType: 'Карты',
    size: '850 MB',
    downloads: 34120,
    rating: 4.5,
    version: '1.0',
  },
  {
    id: 5,
    name: "Garry's Mod - Оригинал",
    category: 'games',
    game: "Garry's Mod",
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '5.2 GB',
    downloads: 87650,
    rating: 4.8,
    version: '2023.11',
  },
  {
    id: 16,
    name: "Garry's Mod - Сборка с аддонами",
    category: 'games',
    game: "Garry's Mod",
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '12.5 GB',
    downloads: 67890,
    rating: 4.7,
    version: '2023.11',
  },
  {
    id: 6,
    name: "Garry's Mod - Оружейный пак",
    category: 'games',
    game: "Garry's Mod",
    contentType: 'mods',
    downloadType: null,
    modType: 'Оружие',
    size: '2.1 GB',
    downloads: 56340,
    rating: 4.7,
    version: '1.0',
  },
  {
    id: 7,
    name: 'Minecraft - Оригинал',
    category: 'games',
    game: 'Minecraft',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '1.2 GB',
    downloads: 234567,
    rating: 5.0,
    version: '1.20.4',
  },
  {
    id: 17,
    name: 'Minecraft - Сборка с модами',
    category: 'games',
    game: 'Minecraft',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '3.8 GB',
    downloads: 189450,
    rating: 4.9,
    version: '1.20.4',
  },
  {
    id: 8,
    name: 'Minecraft - Скрипт автоматизации',
    category: 'games',
    game: 'Minecraft',
    contentType: 'scripts',
    downloadType: null,
    modType: null,
    size: '650 MB',
    downloads: 89450,
    rating: 4.8,
    version: '1.0',
  },
  {
    id: 9,
    name: 'Terraria - Оригинал',
    category: 'games',
    game: 'Terraria',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '450 MB',
    downloads: 156780,
    rating: 4.9,
    version: '1.4.4',
  },
  {
    id: 18,
    name: 'Terraria - Сборка с модами',
    category: 'games',
    game: 'Terraria',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '1.2 GB',
    downloads: 123456,
    rating: 4.8,
    version: '1.4.4',
  },
  {
    id: 10,
    name: 'Terraria - Читы на ресурсы',
    category: 'games',
    game: 'Terraria',
    contentType: 'cheats',
    downloadType: null,
    modType: null,
    size: '45 MB',
    downloads: 67890,
    rating: 4.6,
    version: '1.0',
  },
  {
    id: 11,
    name: 'GTA SA - Пак оружия',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'mods',
    downloadType: null,
    modType: 'Оружие',
    size: '2.5 GB',
    downloads: 15420,
    rating: 4.8,
    version: '3.2',
  },
  {
    id: 12,
    name: 'GTA SA - Lamborghini Aventador',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'mods',
    downloadType: null,
    modType: 'Транспорт',
    size: '150 MB',
    downloads: 23456,
    rating: 4.7,
    version: '1.5',
  },
  {
    id: 13,
    name: 'Minecraft - Пак скинов',
    category: 'games',
    game: 'Minecraft',
    contentType: 'mods',
    downloadType: null,
    modType: 'Скины',
    size: '45 MB',
    downloads: 12890,
    rating: 4.6,
    version: '2.0',
  },
];