export const gamesList = ['GTA San Andreas', 'The Sims 4', "Garry's Mod", 'Minecraft', 'Terraria'];

export const contentTypes = [
  { id: 'download', name: 'Скачать', icon: 'Download', subcategories: ['Оригинал', 'Сборка'] },
  { id: 'mods', name: 'Моды', icon: 'Package', subcategories: ['Оружие', 'Транспорт', 'Карты', 'Скины', 'Персонажи'] },
  { id: 'scripts', name: 'Скрипты', icon: 'Code' },
  { id: 'cheats', name: 'Читы', icon: 'Shield' },
  { id: 'info', name: 'Информация', icon: 'Info' },
];

export const categories = [
  { id: 'games', name: 'Игры', icon: 'Gamepad2', color: 'text-[hsl(var(--primary))]' },
];

export const mockFiles = [
  {
    id: 1,
    name: 'GTA San Andreas - Оригинал',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '4.7 GB',
    downloads: 125420,
    rating: 4.9,
    version: '1.0',
    fileUrl: 'https://drive.google.com/uc?export=download&id=1K39kTz6Eoof3wD24SnBQKGkbAKIajyQd',
    fileType: 'direct',
  },
  {
    id: 2,
    name: 'GTA San Andreas - Сборка',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '8.2 GB',
    downloads: 98340,
    rating: 4.8,
    version: '2.0',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 3,
    name: 'GTA San Andreas - Аддоны',
    category: 'games',
    game: 'GTA San Andreas',
    contentType: 'mods',
    downloadType: null,
    modType: 'Карты',
    size: '1.5 GB',
    downloads: 45230,
    rating: 4.7,
    version: '1.0',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 4,
    name: 'The Sims 4 - Оригинал',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'download',
    downloadType: 'Оригинал',
    modType: null,
    size: '18 GB',
    downloads: 98340,
    rating: 4.7,
    version: '1.98',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 5,
    name: 'The Sims 4 - Сборка со всеми DLC',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'download',
    downloadType: 'Сборка',
    modType: null,
    size: '45 GB',
    downloads: 156780,
    rating: 4.9,
    version: '1.98',
    fileUrl: '',
    fileType: 'direct',
  },
  {
    id: 6,
    name: 'The Sims 4 - Аддоны',
    category: 'games',
    game: 'The Sims 4',
    contentType: 'mods',
    downloadType: null,
    modType: 'Карты',
    size: '2.3 GB',
    downloads: 34120,
    rating: 4.6,
    version: '1.0',
    fileUrl: '',
    fileType: 'direct',
  },
];